// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dfa_cpp
List dfa_cpp(NumericVector x, int nfit, int minbox, int maxbox, bool integrate, bool sliding_window);
RcppExport SEXP _Rtractor_dfa_cpp(SEXP xSEXP, SEXP nfitSEXP, SEXP minboxSEXP, SEXP maxboxSEXP, SEXP integrateSEXP, SEXP sliding_windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nfit(nfitSEXP);
    Rcpp::traits::input_parameter< int >::type minbox(minboxSEXP);
    Rcpp::traits::input_parameter< int >::type maxbox(maxboxSEXP);
    Rcpp::traits::input_parameter< bool >::type integrate(integrateSEXP);
    Rcpp::traits::input_parameter< bool >::type sliding_window(sliding_windowSEXP);
    rcpp_result_gen = Rcpp::wrap(dfa_cpp(x, nfit, minbox, maxbox, integrate, sliding_window));
    return rcpp_result_gen;
END_RCPP
}
// perm_entropy_raw_cpp
double perm_entropy_raw_cpp(NumericVector x, int order, int delay);
RcppExport SEXP _Rtractor_perm_entropy_raw_cpp(SEXP xSEXP, SEXP orderSEXP, SEXP delaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type delay(delaySEXP);
    rcpp_result_gen = Rcpp::wrap(perm_entropy_raw_cpp(x, order, delay));
    return rcpp_result_gen;
END_RCPP
}
// mfdma_fluctuations_cpp
List mfdma_fluctuations_cpp(NumericVector y, IntegerVector scales, double theta);
RcppExport SEXP _Rtractor_mfdma_fluctuations_cpp(SEXP ySEXP, SEXP scalesSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type scales(scalesSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(mfdma_fluctuations_cpp(y, scales, theta));
    return rcpp_result_gen;
END_RCPP
}
// chhabra_jensen_moments_cpp
List chhabra_jensen_moments_cpp(NumericVector timeseries, NumericVector q_values, IntegerVector scales);
RcppExport SEXP _Rtractor_chhabra_jensen_moments_cpp(SEXP timeseriesSEXP, SEXP q_valuesSEXP, SEXP scalesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type timeseries(timeseriesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q_values(q_valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type scales(scalesSEXP);
    rcpp_result_gen = Rcpp::wrap(chhabra_jensen_moments_cpp(timeseries, q_values, scales));
    return rcpp_result_gen;
END_RCPP
}
// petrosian_fd_cpp
double petrosian_fd_cpp(NumericVector x);
RcppExport SEXP _Rtractor_petrosian_fd_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(petrosian_fd_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// num_zerocross_cpp
int num_zerocross_cpp(NumericVector x);
RcppExport SEXP _Rtractor_num_zerocross_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(num_zerocross_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// hjorth_cpp
NumericVector hjorth_cpp(NumericVector x);
RcppExport SEXP _Rtractor_hjorth_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hjorth_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// higuchi_length_cpp
NumericVector higuchi_length_cpp(NumericVector serie, int kmax);
RcppExport SEXP _Rtractor_higuchi_length_cpp(SEXP serieSEXP, SEXP kmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type serie(serieSEXP);
    Rcpp::traits::input_parameter< int >::type kmax(kmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(higuchi_length_cpp(serie, kmax));
    return rcpp_result_gen;
END_RCPP
}
// recurrence_microstate_entropy_cpp
List recurrence_microstate_entropy_cpp(NumericVector serie, IntegerVector x_idx, IntegerVector y_idx, int block, double eps_min, double eps_max, int frac, int frac2);
RcppExport SEXP _Rtractor_recurrence_microstate_entropy_cpp(SEXP serieSEXP, SEXP x_idxSEXP, SEXP y_idxSEXP, SEXP blockSEXP, SEXP eps_minSEXP, SEXP eps_maxSEXP, SEXP fracSEXP, SEXP frac2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type serie(serieSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_idx(x_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y_idx(y_idxSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type eps_min(eps_minSEXP);
    Rcpp::traits::input_parameter< double >::type eps_max(eps_maxSEXP);
    Rcpp::traits::input_parameter< int >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< int >::type frac2(frac2SEXP);
    rcpp_result_gen = Rcpp::wrap(recurrence_microstate_entropy_cpp(serie, x_idx, y_idx, block, eps_min, eps_max, frac, frac2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rtractor_dfa_cpp", (DL_FUNC) &_Rtractor_dfa_cpp, 6},
    {"_Rtractor_perm_entropy_raw_cpp", (DL_FUNC) &_Rtractor_perm_entropy_raw_cpp, 3},
    {"_Rtractor_mfdma_fluctuations_cpp", (DL_FUNC) &_Rtractor_mfdma_fluctuations_cpp, 3},
    {"_Rtractor_chhabra_jensen_moments_cpp", (DL_FUNC) &_Rtractor_chhabra_jensen_moments_cpp, 3},
    {"_Rtractor_petrosian_fd_cpp", (DL_FUNC) &_Rtractor_petrosian_fd_cpp, 1},
    {"_Rtractor_num_zerocross_cpp", (DL_FUNC) &_Rtractor_num_zerocross_cpp, 1},
    {"_Rtractor_hjorth_cpp", (DL_FUNC) &_Rtractor_hjorth_cpp, 1},
    {"_Rtractor_higuchi_length_cpp", (DL_FUNC) &_Rtractor_higuchi_length_cpp, 2},
    {"_Rtractor_recurrence_microstate_entropy_cpp", (DL_FUNC) &_Rtractor_recurrence_microstate_entropy_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rtractor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
