# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
dfa_cpp <- function(x, nfit = 2L, minbox = 0L, maxbox = 0L, integrate = TRUE, sliding_window = FALSE) {
    .Call(`_Rtractor_dfa_cpp`, x, nfit, minbox, maxbox, integrate, sliding_window)
}

#' @keywords internal
fnn_fraction_cpp <- function(x, tau, dims, rtol, atol, theiler) {
    .Call(`_Rtractor_fnn_fraction_cpp`, x, tau, dims, rtol, atol, theiler)
}

#' @keywords internal
perm_entropy_raw_cpp <- function(x, order = 3L, delay = 1L) {
    .Call(`_Rtractor_perm_entropy_raw_cpp`, x, order, delay)
}

#' @keywords internal
mfdma_fluctuations_cpp <- function(y, scales, theta) {
    .Call(`_Rtractor_mfdma_fluctuations_cpp`, y, scales, theta)
}

#' @keywords internal
chhabra_jensen_moments_cpp <- function(timeseries, q_values, scales) {
    .Call(`_Rtractor_chhabra_jensen_moments_cpp`, timeseries, q_values, scales)
}

#' @keywords internal
petrosian_fd_cpp <- function(x) {
    .Call(`_Rtractor_petrosian_fd_cpp`, x)
}

#' @keywords internal
num_zerocross_cpp <- function(x) {
    .Call(`_Rtractor_num_zerocross_cpp`, x)
}

#' @keywords internal
hjorth_cpp <- function(x) {
    .Call(`_Rtractor_hjorth_cpp`, x)
}

#' @keywords internal
higuchi_length_cpp <- function(serie, kmax) {
    .Call(`_Rtractor_higuchi_length_cpp`, serie, kmax)
}

#' @keywords internal
recurrence_microstate_entropy_cpp <- function(serie, x_idx, y_idx, block, eps_min, eps_max, frac, frac2) {
    .Call(`_Rtractor_recurrence_microstate_entropy_cpp`, serie, x_idx, y_idx, block, eps_min, eps_max, frac, frac2)
}

#' @keywords internal
distance_matrix_cpp <- function(traj, norm_code) {
    .Call(`_Rtractor_distance_matrix_cpp`, traj, norm_code)
}

#' @keywords internal
rqa_line_stats_cpp <- function(R, theiler_window) {
    .Call(`_Rtractor_rqa_line_stats_cpp`, R, theiler_window)
}

#' @keywords internal
sample_entropy_counts_cpp <- function(y, m, tolerance) {
    .Call(`_Rtractor_sample_entropy_counts_cpp`, y, m, tolerance)
}

#' @keywords internal
sda_fluctuation_cpp <- function(x, scales) {
    .Call(`_Rtractor_sda_fluctuation_cpp`, x, scales)
}

